name: Build and deploy container app via Terraform

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create private key from secret
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > terraform/github_actions
          chmod 600 terraform/github_actions

      - name: LS
        run: |
          ls -a
          cd terraform
          ls -a 
          cat github_actions
        shell: bash

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
       
      - name: Terraform Apply
        env:
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_ssh_private_key_path: ${{ secrets.SSH_PRIVATE_KEY_PATH }}
          TF_VAR_ssh_port: ${{ secrets.SSH_PORT }}
          TF_VAR_dotenv: ${{ secrets.DOTENV_KEY }}
          TF_VAR_docker_token: ${{ secrets.DOCKER_TOKEN }}

        run: terraform apply -auto-approve
        working-directory: terraform
