# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - bot-discord

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_156738ff1a06440ea557694bffb51822 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f099b1631bee495487afc1c67eb73dce }}

    - name: Build and push container image to registry presi11
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: presi11/discord-bot:${{ github.sha }}
        file: ./docker/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'bot-discord'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e825247fe477487e8438753b63054598 }}
        images: 'presi11/discord-bot:${{ github.sha }}'
