name: Build and deploy container app via Terraform

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -f docker/Dockerfile -t jonathanstrf/botrucho:1.1.4 .
          docker save jonathanstrf/botrucho:1.1.4 > botrucho.tar

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        env:
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_VAR_dotenv: ${{ secrets.DOTENV_KEY }}
        run: terraform apply -auto-approve
        working-directory: terraform
