name: Build and deploy container app via Terraform

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: print secrets
        run: |
            echo $SSH_PRIVATE_KEY &gt;&gt; terraform/github_actions
            cat terraform/github_actions
        shell: bash
        env:
          SSH_PRIVATE_KEY : ${{secrets.SSH_PRIVATE_KEY}}

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
       
      - name: Terraform Apply
        env:
          TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
          TF_VAR_ssh_host: ${{ secrets.SSH_HOST }}
          TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_VAR_ssh_port: ${{ secrets.SSH_PORT }}
          TF_VAR_dotenv: ${{ secrets.DOTENV_KEY }}
        run: terraform apply -auto-approve
        working-directory: terraform
