name: Trigger Portainer via Tailscale

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/botrucho

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64, linux/arm64
          file: docker/Dockerfile
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 3
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}
          tailscale ip

      - name: Call Portainer webhook
        run: |
          curl -X POST http://100.92.18.76:9000/api/webhooks/536639cb-d9bd-4fe9-8c5a-94e4a62267fa

      - name: Cleanup Tailscale
        if: always()
        run: |
          sudo tailscale logout
