name: Trigger Portainer via Tailscale

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Install Tailscale
      run: |
        curl -fsSL https://tailscale.com/install.sh | sh

    - name: Start Tailscale
      run: |
        sudo tailscaled &
        sleep 3
        sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }}
        tailscale ip

    - name: Call Portainer webhook
      run: |
        curl -X POST http://100.92.18.76:9000/api/webhooks/372fd5f2-e602-4928-890f-cf7422b59e8c

    - name: Cleanup Tailscale
      if: always()
      run: |
        sudo tailscale logout
